# Part of the backend risk models -- an algorithm-comparison experiment
# for the dissertation's evaluation chapter. Doesn't touch the live app.
"""
Compares the deterministic rule, Logistic Regression, a single Decision
Tree, and the existing trained Random Forest (loaded from disk, never
retrained here), plus the text model if its saved file exists.

Worth remembering when quoting these numbers: risk_label in train.csv/
test.csv is generated by a rule over exactly these six structured
features, so what's measured here is how well each algorithm reproduces
that rule, not clinical predictive accuracy.

This script never imports or changes main.py or comparison_engine.py,
never touches train.csv/test.csv, and never overwrites rf_model.joblib,
text_model.joblib, or evaluation_summary.json -- it only reads existing
files and writes two new ones (baseline_comparison_results.json/.csv).

The deterministic-rule check below reads the feature columns already in
train.csv/test.csv rather than importing generate_synthetic_data.py's
labelling code directly, so it's technically its own small copy of the
same rule -- fine for this one standalone comparison, but not something
to reuse elsewhere.

Run with: python backend/risk_models/baseline_comparison.py
"""
import os
import sys
import json

import joblib
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support, confusion_matrix, f1_score
)

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
DATA_DIR = os.path.join(HERE, "..", "..", "data")
TRAIN_PATH = os.path.join(DATA_DIR, "train.csv")
TEST_PATH = os.path.join(DATA_DIR, "test.csv")
RF_MODEL_PATH = os.path.join(HERE, "rf_model.joblib")
TEXT_MODEL_PATH = os.path.join(HERE, "text_model.joblib")
OUT_JSON = os.path.join(HERE, "baseline_comparison_results.json")
OUT_CSV = os.path.join(HERE, "baseline_comparison_results.csv")

import train_random_forest as rf_module  # noqa: E402 -- reuses to_xy(); never retrains the saved model
from evaluate import under_over_risked  # noqa: E402 -- reuses the exact same under/over-risk logic

LABEL = "risk_label"
CLASS_ORDER = ["NONE", "LOW", "MEDIUM", "HIGH"]


def deterministic_rule_predict(df):
    """Re-applies the same rule that generated risk_label, reading it back
    from the feature columns. Should match risk_label 100% of the time --
    that's the point, this is the reference everything else is measured
    against, not a model competing on equal footing."""
    preds = []
    for _, row in df.iterrows():
        drug_changed = bool(row["drug_changed"])
        formulation_changed = bool(row["formulation_changed"])
        dose_changed = bool(row["dose_changed"])
        route_changed = bool(row["route_changed"])
        nti = bool(row["narrow_therapeutic_index"])
        pct = row["dose_change_pct"]

        if not (drug_changed or formulation_changed or dose_changed or route_changed):
            preds.append("NONE")
        elif drug_changed:
            preds.append("HIGH" if nti else "MEDIUM")
        elif formulation_changed:
            preds.append("HIGH" if nti else "MEDIUM")
        elif dose_changed:
            threshold = 0.25 if nti else 0.50
            preds.append("HIGH" if abs(pct) >= threshold else ("MEDIUM" if nti else "LOW"))
        elif route_changed:
            preds.append("LOW")
        else:
            preds.append("NONE")
    return preds


def report_metrics(name, y_true, y_pred, notes=""):
    acc = accuracy_score(y_true, y_pred)
    precision, recall, f1_macro, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0, labels=CLASS_ORDER
    )
    f1_weighted = f1_score(y_true, y_pred, average="weighted", zero_division=0, labels=CLASS_ORDER)
    cm = confusion_matrix(y_true, y_pred, labels=CLASS_ORDER)
    under, over = under_over_risked(list(y_true), list(y_pred))

    print("=" * 70)
    print(name)
    if notes:
        print(notes)
    print("-" * 70)
    print(f"Accuracy:         {acc:.4f}")
    print(f"Macro precision:  {precision:.4f}")
    print(f"Macro recall:     {recall:.4f}")
    print(f"Macro F1:         {f1_macro:.4f}")
    print(f"Weighted F1:      {f1_weighted:.4f}")
    print(f"Under-risked:     {under}")
    print(f"Over-risked:      {over}")
    print(f"Confusion matrix (rows=true, cols=pred), labels {CLASS_ORDER}:")
    print(cm)
    print()

    return {
        "model": name,
        "accuracy": round(float(acc), 4),
        "macro_precision": round(float(precision), 4),
        "macro_recall": round(float(recall), 4),
        "macro_f1": round(float(f1_macro), 4),
        "weighted_f1": round(float(f1_weighted), 4),
        "under_risked": int(under),
        "over_risked": int(over),
        "confusion_matrix": cm.tolist(),
        "confusion_matrix_labels": CLASS_ORDER,
        "notes": notes,
    }


def main():
    print(__doc__)

    train_df = pd.read_csv(TRAIN_PATH)
    test_df = pd.read_csv(TEST_PATH)
    y_train = train_df[LABEL]
    y_test = test_df[LABEL]

    X_train, _ = rf_module.to_xy(train_df)
    X_test, _ = rf_module.to_xy(test_df)

    results = []

    # 1. Deterministic reference rule --------------------------------------
    rule_preds = deterministic_rule_predict(test_df)
    results.append(report_metrics(
        "1. Deterministic reference rule",
        y_test, rule_preds,
        notes="Reapplies the exact rule that generated risk_label -- included as the reference "
              "framework baseline, not a competing model.",
    ))

    # 2. Logistic Regression -------------------------------------------------
    logreg = Pipeline([
        ("scale", StandardScaler()),
        ("clf", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)),
    ])
    logreg.fit(X_train, y_train)
    results.append(report_metrics(
        "2. Logistic Regression",
        y_test, logreg.predict(X_test),
        notes="StandardScaler on all 6 features (dose_change_pct is continuous while the other 5 "
              "are 0/1 booleans on a different natural scale) -> LogisticRegression(max_iter=1000, "
              "class_weight='balanced', random_state=42). Multinomial softmax via the default "
              "lbfgs solver (sklearn's current default multiclass handling for this solver).",
    ))

    # 3. Single Decision Tree -------------------------------------------------
    tree = DecisionTreeClassifier(random_state=42, class_weight="balanced")
    tree.fit(X_train, y_train)
    results.append(report_metrics(
        "3. Decision Tree (single)",
        y_test, tree.predict(X_test),
        notes=f"DecisionTreeClassifier(random_state=42, class_weight='balanced'); no max_depth cap "
              f"imposed -- left to grow to whatever depth the data naturally requires, rather than "
              f"tuned toward a target score. Actual depth reached: {tree.get_depth()}, "
              f"leaves: {tree.get_n_leaves()}.",
    ))

    # 4. Existing Random Forest -- loaded, NOT retrained ------------------------
    if os.path.exists(RF_MODEL_PATH):
        rf = joblib.load(RF_MODEL_PATH)
        results.append(report_metrics(
            "4. Random Forest (existing saved model -- loaded, not retrained)",
            y_test, rf.predict(X_test),
            notes="Loaded directly from rf_model.joblib, exactly as used by the live application "
                  "(n_estimators=200, max_depth=8, random_state=42, class_weight='balanced'). "
                  "Not retrained, refit, or altered by this script.",
        ))
    else:
        print("rf_model.joblib not found -- run backend/risk_models/evaluate.py first. Skipping.\n")

    # 5. Existing text model, if present ---------------------------------------
    if os.path.exists(TEXT_MODEL_PATH):
        import train_text_classifier as text_module
        text_model = joblib.load(TEXT_MODEL_PATH)
        sentences = text_module.build_sentences(test_df)
        results.append(report_metrics(
            "5. Text model (existing saved TF-IDF + LogReg -- loaded, not retrained)",
            y_test, text_model.predict(sentences),
            notes="Loaded directly from text_model.joblib. Given only the natural-language "
                  "sentence describing the change, not the structured features directly -- "
                  "included for completeness alongside the structured-feature models above, not "
                  "as a variant of them.",
        ))
    else:
        print("text_model.joblib not found -- skipping (optional).\n")

    # --- 5-fold stratified cross-validation, train.csv only, test.csv untouched ---
    print("=" * 70)
    print("5-FOLD STRATIFIED CROSS-VALIDATION (train.csv only -- test.csv never touched)")
    print("=" * 70)
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_models = {
        "Logistic Regression": Pipeline([
            ("scale", StandardScaler()),
            ("clf", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)),
        ]),
        "Decision Tree": DecisionTreeClassifier(random_state=42, class_weight="balanced"),
        "Random Forest": RandomForestClassifier(
            n_estimators=200, max_depth=8, random_state=42, class_weight="balanced"
        ),
    }
    cv_results = {}
    for name, model in cv_models.items():
        scores = cross_val_score(model, X_train, y_train, cv=cv, scoring="accuracy")
        mean, std = float(scores.mean()), float(scores.std())
        print(f"{name:22s} mean accuracy = {mean:.4f}  (std = {std:.4f})  "
              f"folds = {np.round(scores, 4).tolist()}")
        cv_results[name] = {
            "mean_accuracy": round(mean, 4),
            "std_accuracy": round(std, 4),
            "fold_scores": [round(float(s), 4) for s in scores],
        }
    print()

    # --- save -----------------------------------------------------------------
    output = {
        "academic_note": (
            "risk_label in train.csv/test.csv is generated by a deterministic rule over exactly "
            "these same structured features (see data/generate_synthetic_data.py). These results "
            "measure each algorithm's ability to reproduce that reference framework, NOT clinical "
            "predictive validity. See ALGORITHM_AUDIT_3.md for full discussion."
        ),
        "train_size": len(train_df),
        "test_size": len(test_df),
        "features_used": list(X_train.columns),
        "test_set_results": results,
        "cross_validation_5fold_stratified_on_train": cv_results,
    }
    with open(OUT_JSON, "w") as f:
        json.dump(output, f, indent=2)
    print(f"Saved -> {OUT_JSON}")

    csv_rows = [
        {k: v for k, v in r.items() if k not in ("confusion_matrix", "confusion_matrix_labels", "notes")}
        for r in results
    ]
    pd.DataFrame(csv_rows).to_csv(OUT_CSV, index=False)
    print(f"Saved -> {OUT_CSV}")


if __name__ == "__main__":
    main()
